"""[ARCHIVED] Code-Factory runtime: loads and executes cached cluster extraction scripts.

Status: ARCHIVED — 20.9% KILE on 50-doc. Structurally impossible to produce
PCC-aligned bboxes because generated Python operates on text strings without
access to DocILE's snapped OCR word grid. See KNOWLEDGE_BASE.md §6.15 for details.

Build-time scripts generated by tools/build_cluster_scripts.py (per cluster).
Hard limits: restricted sandbox (only `re` + `WordBox`), 5s thread timeout.
"""

from __future__ import annotations

import json
import re
import threading
from pathlib import Path
from typing import Any

from docile.dataset import BBox, Field

from .data import WordBox
from .extract import _KILE_TYPES, _LIR_TYPES

SCRIPTS_DIR = Path(__file__).parent.parent.parent / "models" / "code_factory_scripts"
METADATA_PATH = SCRIPTS_DIR / "_metadata.json"


# ── Metadata helpers ──────────────────────────────────────────────────────────


def load_metadata() -> dict[str, Any]:
    if METADATA_PATH.exists():
        return json.loads(METADATA_PATH.read_text())
    return {}


def save_metadata(meta: dict[str, Any]) -> None:
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    METADATA_PATH.write_text(json.dumps(meta, indent=2))


def script_path(cluster_id: int) -> Path:
    return SCRIPTS_DIR / f"{cluster_id}.py"


def has_script(cluster_id: int) -> bool:
    return script_path(cluster_id).exists()


# ── Sandbox execution ──────────────────────────────────────────────────────────


def _run_with_timeout(fn, args: tuple, timeout: float = 5.0):
    """Execute fn(*args) in a daemon thread; raise TimeoutError if it exceeds timeout."""
    result: list[Any] = [None]
    error: list[BaseException | None] = [None]

    def _target():
        try:
            result[0] = fn(*args)
        except Exception as e:
            error[0] = e

    t = threading.Thread(target=_target, daemon=True)
    t.start()
    t.join(timeout)
    if t.is_alive():
        raise TimeoutError(f"Script exceeded {timeout:.1f}s")
    if error[0] is not None:
        raise error[0]
    return result[0]


def run_script(
    cluster_id: int,
    words: list[WordBox],
    timeout: float = 5.0,
) -> list[dict] | None:
    """Execute cached extraction script for cluster_id on words.

    Returns validated list of {fieldtype, word_ids} dicts, or None on any error.
    The sandbox allows only `re` and `WordBox` — no file I/O, no network.
    """
    path = script_path(cluster_id)
    if not path.exists():
        return None

    code = path.read_text()
    sandbox: dict[str, Any] = {"re": re, "WordBox": WordBox}
    try:
        exec(compile(code, str(path), "exec"), sandbox)
    except Exception:
        return None

    extract_fn = sandbox.get("extract")
    if not callable(extract_fn):
        return None

    try:
        raw = _run_with_timeout(extract_fn, (words,), timeout=timeout)
    except Exception:
        return None

    if not isinstance(raw, list):
        return None

    valid: list[dict] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        ft = item.get("fieldtype", "")
        word_ids = item.get("word_ids", [])
        if ft not in _KILE_TYPES and ft not in _LIR_TYPES:
            continue
        if not isinstance(word_ids, list):
            continue
        if not all(isinstance(w, int) for w in word_ids):
            continue
        valid.append({"fieldtype": ft, "word_ids": word_ids})

    return valid


# ── Convert script output → Field objects ─────────────────────────────────────


def _merge_bboxes(word_ids: list[int], words: list[WordBox]) -> BBox | None:
    id_to_word = {w.id: w for w in words}
    bboxes = [id_to_word[wid].bbox for wid in word_ids if wid in id_to_word]
    if not bboxes:
        return None
    return BBox(
        min(b[0] for b in bboxes),
        min(b[1] for b in bboxes),
        max(b[2] for b in bboxes),
        max(b[3] for b in bboxes),
    )


def results_to_fields(
    results: list[dict],
    words: list[WordBox],
    page_idx: int,
    score: float = 0.9,
) -> tuple[list[Field], list[Field]]:
    """Convert script output dicts to (kile_fields, lir_fields) Field objects."""
    kile: list[Field] = []
    lir: list[Field] = []

    for item in results:
        ft = item.get("fieldtype", "")
        word_ids = item.get("word_ids", [])
        line_item_id = item.get("line_item_id")

        bbox = _merge_bboxes(word_ids, words)
        if bbox is None:
            continue

        text_parts = []
        id_set = set(word_ids)
        for w in words:
            if w.id in id_set:
                text_parts.append(w.text)
        text = " ".join(text_parts)

        f = Field(
            bbox=bbox,
            page=page_idx,
            fieldtype=ft,
            score=score,
            line_item_id=line_item_id,
            text=text,
        )

        if ft in _LIR_TYPES:
            lir.append(f)
        else:
            kile.append(f)

    return kile, lir


# ── High-level: extract one document using Code-Factory ───────────────────────


def extract_doc_with_scripts(
    pages_words: list[list[WordBox]],
    cluster_id: int,
    script_timeout: float = 5.0,
) -> tuple[list[Field], list[Field]] | None:
    """Run Code-Factory script on all pages; return (kile_fields, lir_fields) or None.

    Returns None if no script exists for this cluster or all pages returned 0 hits.
    Caller should fall back to V5b on None.
    """
    if not has_script(cluster_id):
        return None

    all_kile: list[Field] = []
    all_lir: list[Field] = []
    any_hit = False

    for page_idx, words in enumerate(pages_words):
        results = run_script(cluster_id, words, timeout=script_timeout)
        if results is None:
            continue
        if results:
            any_hit = True
        kile, lir = results_to_fields(results, words, page_idx)
        all_kile.extend(kile)
        all_lir.extend(lir)

    if not any_hit:
        return None

    return all_kile, all_lir
